// Generated by CoffeeScript 1.8.0
var ExsCheck, FontAwesome, React, ko, ok;

React = require('react');

FontAwesome = require('react-fontawesome');

ok = React.createClass({
  render: function() {
    return React.createElement(FontAwesome, {
      name: "check",
      style: {
        color: "green"
      }
    });
  }
});

ko = React.createClass({
  render: function() {
    return React.createElement(FontAwesome, {
      name: "check",
      style: {
        color: "red"
      }
    });
  }
});

module.exports = ExsCheck = React.createClass({
  render: function() {
    var div, i, p, span, _ref;
    _ref = React.DOM, span = _ref.span, p = _ref.p, div = _ref.div, i = _ref.i;
    return div(null, this.props.tests.map(function(x) {
      return div(null, span(null, x.display), x.test() ? React.createElement(ok) : React.createElement(ko));
    }));
  }
});
