// Generated by CoffeeScript 1.8.0
var channel, outcome;

channel = void 0;

outcome = false;

window.getState = function() {
  return JSON.stringify({});
};

window.getGrade = function() {
  return JSON.stringify(outcome);
};

if (window.parent !== window) {
  channel = window.channel = Channel.build({
    window: window.parent,
    origin: "*",
    scope: "JSInput"
  });
  channel.bind("getGrade", function() {
    return window.getGrade.apply(null, arguments);
  });
  channel.bind("getState", function() {
    return window.getState.apply(null, arguments);
  });
}
